<div id="page">  
    <div id="head">Tonos</div>
    <div id="publicidad"> 		
        <img width="100%" src="<?php echo STATIC_URL ?>img/rt/banner-nextel-tonos.jpg">               
    </div>  
    <div id="list-titulo-precio">      
        Te est&aacute;s suscribiendo al servicio de Tonos, cada semana podr&aacute;s descargar el tono que desees. Costo US$ 1.80 por suscripci&oacute;n semanal.
        <div class="btn-ancho" style="text-align: center;color: #FFFFFF;font-weight: bold;margin: 20px auto;border-radius: 4px;padding: 3px;-moz-box-sizing: border-box;border: medium none;" >
            <a style="color: #FFFFFF; font-size: 14px;background-color:#E05206;font-weight:bold;" href="/pe/ne/wap/rt-devel/gor?link=<? echo $this->link ?>">ACEPTAS DESCARGAR EL TONO</a>
        </div>
    </div>  
</div>
