<div id="page">
    <div id="head"><?PHP echo $this->TituloPortal; ?></div>
    <?PHP if (count($this->DESTACADOs) > 0) { ?>
        <?PHP
        foreach ($this->DESTACADOs as $destacado) {
            $dataContenido = $this->dataContenido;
            foreach ($dataContenido as $item) {
                ?>
                <div id="destacado">
                    <img src="<?php echo STATIC_URL ?>img/<?= $destacado["RUTAIMAGEN"]; ?>" alt="destacado" /> 
                    <a href="/gor?link=/pe/ne/wap/rt-devel/validacion?v=<? echo $this->val_sms; ?>&c=<?= $item["CodigoRBT"] . "" . $this->nuetxt; ?>&t=<? echo $this->t; ?>&f=<? echo $this->f; ?>&i=<? echo $this->i ?>&nue=<? echo $this->numx; ?>">
                        <?= $item["Tema"]; ?><span><?= $item["Artista"]; ?></span>
                    </a>
                    <div style="clear:both"></div>
                </div>  
            <?PHP } ?>	
            <div id="list-titulo-precio"><? echo htmlspecialchars_decode($destacado["TEXTOENPORTAL"]); ?></div>
            <?PHP
        }
    }
    ?>
    <?php if (isset($this->error) and ( $this->error == "007")) { ?>
        <div id="list-titulo-precio" class="error">Estimado usuario usted no cuenta con saldo necesario o intentelo nuevamente.</div>
    <?php } ?>	
    <?PHP if (count($this->BODYs) > 0) { ?> 
        <?PHP foreach ($this->BODYs as $body) { ?>		
            <div id="list-titulo"><?= $body["TITULOENPORTAL"]; ?></div>
            <div id="list-musica">
                <?PHP
                $dataContenidoBody = $this->dataContenidoBody;
                $count = 1;
                foreach ($dataContenidoBody as $item) {
                    $rowalter = '';
                    if ($count % 2 == 0)
                        $rowalter = " odd";
                    ?>
                    <div class="list-item<?= $rowalter; ?>"> <span class="numero">
                            <?= $count; ?>.</span>
                        <a href="/gor?link=/pe/ne/wap/rt-devel/validacion?v=<? echo $this->val_sms; ?>&c=<?= $item["CodigoRBT"] . "" . $this->nuetxt; ?>&t=<? echo $this->t; ?>&f=<? echo $this->f; ?>&i=<? echo $this->i; ?>&nue=<? echo $this->numx; ?>">
                            <?= $item["Tema"]; ?>
                            <span>
                                <?= $item["Artista"]; ?>
                            </span></a><a href="/gor?link=/pe/ne/wap/rt-devel/validacion?v=<? echo $this->val_sms; ?>&c=<?= $item['CodigoRBT'] . '' . $this->nuetxt; ?>&t=<? echo $this->t; ?>&f=<? echo $this->f; ?>&i=<? echo $this->i; ?>&nue=<? echo $this->numx; ?>" class="descarga"></a>
                        <div style="clear:both"></div>
                    </div>
                    <?PHP
                    $count = $count + 1;
                }
                ?>	
            </div>
            <?PHP
        }
    }
    ?>	
    <div style="margin:5px 10px 0 10px">
        <a href="../ft">  <img width="100%" src="<?php echo STATIC_URL ?>img/rt/banner-musica.gif"></a>
    </div>
    <div id="footer"><a href="http://m.tuyonextel.com.pe">&lt; Volver</a> | 
        <a href="/gor?link=/pe/ne/wap/rt-devel/legal?v=<? echo $this->val_sms; ?>&t=<? echo $this->t ?>&f=<? echo $this->f ?>&i=<? echo $this->i ?>&nue=<? echo $this->numx; ?>">Legal</a>
    </div>
</div>