<div id="page">
    <div id="head">Tonos</div>
    <div id="list-titulo" class="legal">Legal</div>
    <div id="list-musica">

        <div class="list-item marco">

            <p><b>1. Aceptaci&oacute;n de Condiciones</b><br/>
                La utilizaci&oacute;n del servicio aqu&iacute; ofrecido atribuye la condición de Usuario e implica la aceptación de las Condiciones Legales aquí indicadas.
            </p>
            <p><b>2. El Servicio</b><br/>
                El servicio RINGTONE permite a los usuarios contar con diferentes tonos de timbrado y poder personalizarlo de acuerdo a la persona que lo llame.
                Este servicio permite al usuario cambiar de un tono de timbrado cl&aacute;sico a un tono musical, como por ejemplo una canci&oacute;n, sonidos de animales, bromas, voces, etc.

            </p>
            <p><b>3. Modalidad</b><br/>

                El servicio se ofrece en modalidad de suscripci&oacute;n. 
                El usuario se suscribe al servicio haciendo clic en Aceptary todas las semanas se le enviar&aacute; un link para que ingrese al portal de tonos y elija el tono que desee descargar. Haciendo clic en el tono se realiza la descarga autom&aacute;tica de la misma.
                Para cancelar el servicio el usuario debe enviar un mensaje de texto con la palabra SALIR al 4556.
            </p>
            <p><b>4. Tarifas</b><br/>
                Costo por tono semanal: USD 1.80 inc. IGV.
                El usuario puede descargarse el tono que desee cada semana.
            </p>
            <p><b>5. Celulares Soportados</b><br/>
                Todos los equipos 3G de Nextel y planes Nextel + a nivel nacional.
            </p>
            <p><b>6. Forma de Pago</b><br/>
                Para productos contrato los montos se facturan de manera adicional al cargo fijo mensual del Usuario. Para productos prepago, los precios por la suscripción le serán debitados al Usuario por el operador telefónico directamente del saldo de su tarjeta prepago.
            </p>
            <p><b>7. Contacto</b><br/>
                <a href="mailto:servicioalcliente@mobilesolutions.pe">servicioalcliente@mobilesolutions.pe</a>
            </p>

            <div style="clear:both"></div>
        </div>

    </div>

    <div id="footer"><a href="/pe/ne/wap/rt-devel/">Volver</a></div>
</div>