<div id="page">  
    <div id="head">Club de M&uacute;sica</div>
    <div id="publicidad"> 		
        <img width="100%" src="<?php echo STATIC_URL ?>img/ft/banner-musica-nextel.gif">               
    </div>  
    <div id="list-titulo-precio">      
        Suscr&iacute;bete para descargar todas las canciones que puedas por solo US$ 0.59 por d&iacute;a.
            <div class="btn-ancho" style="text-align: center;color: #FFFFFF;font-weight: bold;margin: 20px auto;border-radius: 4px;padding: 3px;-moz-box-sizing: border-box;border: medium none;" >
                  <a style="color: #FFFFFF; font-size: 14px;background-color:#E05206;font-weight:bold;" href="/pe/ne/wap/ft/gof?link=<? echo $this->link?>">ACEPTAS DESCARGAR LA CANCION</a>
            </div>
   </div>  
</div>
