<div id="page">
    <div id="head"><?PHP echo $this->TituloPortal; ?></div>
    <?PHP if (count($this->BANERs) > 0) { ?>	
        <div id="BANERs">
            <?PHP foreach ($this->BANERs as $baner) { ?>	
                <div>
                    <a href="<?= $baner["LINK"]; ?>">
                        <img border="0" src="<?= $baner[0]["IMG"]; ?>" name="baner" alt="baner" />
                    </a>
                </div>
            <?PHP } ?>	
        </div>
    <?PHP } ?>	
    <?PHP if (count($this->DESTACADOs) > 0) { ?>
        <?PHP
        foreach ($this->DESTACADOs as $destacado) {
            $dataContenido = $this->dataContenido;
            foreach ($dataContenido as $item) {
                ?>

                <div id="destacado">
                    <img src="<?php echo STATIC_URL ?>img/<?= $destacado["RUTAIMAGEN"]; ?>" alt="destacado" />                          
                    <a href="/gof?link=/pe/ne/wap/ft/validacion?v=<?= $val_sms; ?>&c=<?= $item["CodigoRBT"];?>&nue=<?php echo $this->nuetxt; ?> &t=<? echo $this->t ?>&f=<? echo $this->f ?>>&i=<? echo $this->i ?>"> 
                        <?= $item["Tema"]; ?><span><?= $item["Artista"]; ?></span>
                    </a>
                    <div style="clear:both"></div>
                </div>  
            <?PHP } ?>	
            <div id="list-titulo-precio"><? echo htmlspecialchars_decode($destacado["TEXTOENPORTAL"]); ?></div>
            <?PHP
        }
    }
    ?>	
    <?PHP if (count($this->BODYs) > 0) { ?>
        <?PHP foreach ($this->BODYs as $body) { ?>		
            <div id="list-titulo"><?= $body["TITULOENPORTAL"]; ?></div>
            <div id="list-musica">
                <?PHP
                $dataContenidoBody = $this->dataContenidoBody;
                $count = 1;
                foreach ($dataContenidoBody as $item) {
                    $rowalter = '';
                    if ($count % 2 == 0)
                        $rowalter = " odd";
                    ?>

                    <div class="list-item<?= $rowalter; ?>"> <span class="numero">
                            <?= $count; ?>
                             .</span> <a href="/gof?link=/pe/ne/wap/ft/validacion?v=<?= $val_sms; ?>&c=<?= $item["CodigoRBT"] ?>&nue=<?php echo $this->nuetxt; ?>&t=<? echo $this->t ?>&f=<? echo $this->f ?>&i=<? echo $this->i ?>">
                            <?= $item["Tema"]; ?>
                            <span>
                                <?= $item["Artista"]; ?>
                            </span></a><a href="/gof?link=/pe/ne/wap/ft/validacion?v=<?= $val_sms; ?>&c=<?= $item["CodigoRBT"] ?>&nue=<?php echo $this->nuetxt; ?>&t=<? echo $this->t ?>&f=<? echo $this->f ?>>&i=<? echo $this->i ?>" class="descarga"></a>
                        <div style="clear:both"></div>
                    </div>


                    <?PHP $count = $count + 1;
                }
                ?>	
            </div>
            <?PHP
        }
    }
    ?>	
    <div id="footer"><a href="http://m.tuyonextel.com.pe">&lt; Volver</a> | <a href="/pe/ne/wap/ft/legal">Legal</a></div>
</div>